### ISSUE TITLE
Actividad 5 cuadro comparativo diferentes tipos de texto 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-ErikCuevas03#2]
[CARACTERISTICAS DE LOS DIFERENTES TIPO DE TEXTO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-ErikCuevas03/files/9716078/CARACTERISTICAS.DE.LOS.DIFERENTES.TIPO.DE.TEXTO.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación..

**Comment by Daisy-GonzalezLita12** [comment]
10 de 20

**Comment by josealfredo79** [comment]
@Daisy-GonzalezLita12 Favor de calificar correctamente

**Comment by josealfredo79** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
